### PR TITLE
go/badger: bump badger version

### PR DESCRIPTION
**Pull request by ptrus**
TODO:
- [x] run the longtests and comapre cpu/memory/iops usage
  - looks much better during compaction & also fixes cpu spikes at node restarts (there was a bug with badger vlog replay that replayed all vlogs) 
- [x] wait for the 72hours test to finish

### CODE REVIEW

**Comment by kostko** [comment]
Looking at the failure, this may require disabling conflict detection by setting the `WithDetectConflicts(false)` (previously this was implied by managed mode, but now it is not).

**Comment by ptrus** [comment]
> Looking at the failure, this may require disabling conflict detection by setting the WithDetectConflicts(false) (new option, previously this was implied by managed mode, but now it is not).

That fixed the failure, thanks!

**Comment by kostko** [comment]
Just noticed that Badger master has some additional fixes in comparison to rc3.

**Comment by ptrus** [comment]
Ok, bumped badger in this PR to use that commit as well.

**Pull request merged**
